name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


    - name: Login to JFrog 
      uses: docker/login-action@v1
      with:
        registry: omri28.jfrog.io
        username: github
        password: ${{ secrets.JF_ACCESS_TOKEN}}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: omri28.jfrog.io/moshe5:latest
